import { Html, useGLTF } from "@react-three/drei";
import { useAtom } from "jotai";
import React from "react";
import { degToRad } from "three/src/math/MathUtils";
import { currentPageAtom } from "./UI";

const OverlayItem = ({
  className = "",
  title,
  description,
  price,
  bgColor,
  ...props
}) => {
  const [currentPage] = useAtom(currentPageAtom);
  return (
    <Html
      transform
      distanceFactor={1.2}
      center
      className={`w-48 rounded-md overflow-hidden ${
        currentPage === "store" ? "" : "opacity-0"
      } transition-opacity duration-1000 ${className}`}
      {...props}
    >
      <div className="bg-white bg-opacity-50 backdrop-blur-lg text-xs p-2 w-full">
        <h2 className="font-bold">{title}</h2>
        <p>{description}</p>
      </div>
      <button
        className={`${bgColor} hover:bg-opacity-50 transition-colors duration-500 px-4 py-2 font-bold text-white w-full text-xs`}
      >
        Add to cart ${price}
      </button>
    </Html>
  );
};

export function Camping(props) {
  const { nodes, materials } = useGLTF("/models/Camping Asset Collection.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Plane047"
        geometry={nodes.Plane047.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Cube106_Cube114"
        geometry={nodes.Cube106_Cube114.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube105_Cube113"
        geometry={nodes.Cube105_Cube113.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube104_Cube112"
        geometry={nodes.Cube104_Cube112.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube103_Cube111"
        geometry={nodes.Cube103_Cube111.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube102_Cube110"
        geometry={nodes.Cube102_Cube110.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube101_Cube109"
        geometry={nodes.Cube101_Cube109.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube100_Cube108"
        geometry={nodes.Cube100_Cube108.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube099_Cube107"
        geometry={nodes.Cube099_Cube107.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Icosphere016"
        geometry={nodes.Icosphere016.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere015"
        geometry={nodes.Icosphere015.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere014"
        geometry={nodes.Icosphere014.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere013"
        geometry={nodes.Icosphere013.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere012"
        geometry={nodes.Icosphere012.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere011"
        geometry={nodes.Icosphere011.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere010"
        geometry={nodes.Icosphere010.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere009"
        geometry={nodes.Icosphere009.geometry}
        material={materials.Smoke}
      />
      <mesh
        name="Icosphere008"
        geometry={nodes.Icosphere008.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere007"
        geometry={nodes.Icosphere007.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere006"
        geometry={nodes.Icosphere006.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere005"
        geometry={nodes.Icosphere005.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere004"
        geometry={nodes.Icosphere004.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere003"
        geometry={nodes.Icosphere003.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere002"
        geometry={nodes.Icosphere002.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere001"
        geometry={nodes.Icosphere001.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Icosphere"
        geometry={nodes.Icosphere.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane046"
        geometry={nodes.Plane046.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Cube090_Cube094"
        geometry={nodes.Cube090_Cube094.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube089_Cube093"
        geometry={nodes.Cube089_Cube093.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube088_Cube092"
        geometry={nodes.Cube088_Cube092.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube087_Cube091"
        geometry={nodes.Cube087_Cube091.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube086_Cube090"
        geometry={nodes.Cube086_Cube090.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube085_Cube089"
        geometry={nodes.Cube085_Cube089.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube084_Cube088"
        geometry={nodes.Cube084_Cube088.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube083_Cube087"
        geometry={nodes.Cube083_Cube087.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube082_Cube086"
        geometry={nodes.Cube082_Cube086.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube081_Cube085"
        geometry={nodes.Cube081_Cube085.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube080_Cube084"
        geometry={nodes.Cube080_Cube084.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube079_Cube083"
        geometry={nodes.Cube079_Cube083.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube078_Cube082"
        geometry={nodes.Cube078_Cube082.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube077_Cube081"
        geometry={nodes.Cube077_Cube081.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube076_Cube080"
        geometry={nodes.Cube076_Cube080.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube075_Cube079"
        geometry={nodes.Cube075_Cube079.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube074_Cube078"
        geometry={nodes.Cube074_Cube078.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube073_Cube077"
        geometry={nodes.Cube073_Cube077.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube072_Cube076"
        geometry={nodes.Cube072_Cube076.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube071_Cube075"
        geometry={nodes.Cube071_Cube075.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube070_Cube074"
        geometry={nodes.Cube070_Cube074.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube069_Cube073"
        geometry={nodes.Cube069_Cube073.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube068_Cube072"
        geometry={nodes.Cube068_Cube072.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube067_Cube071"
        geometry={nodes.Cube067_Cube071.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube066_Cube070"
        geometry={nodes.Cube066_Cube070.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube065_Cube069"
        geometry={nodes.Cube065_Cube069.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube064_Cube068"
        geometry={nodes.Cube064_Cube068.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube063_Cube067"
        geometry={nodes.Cube063_Cube067.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube062_Cube066"
        geometry={nodes.Cube062_Cube066.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube061_Cube065"
        geometry={nodes.Cube061_Cube065.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube060_Cube064"
        geometry={nodes.Cube060_Cube064.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube059_Cube063"
        geometry={nodes.Cube059_Cube063.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube058_Cube062"
        geometry={nodes.Cube058_Cube062.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube057_Cube061"
        geometry={nodes.Cube057_Cube061.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube056_Cube060"
        geometry={nodes.Cube056_Cube060.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube055_Cube059"
        geometry={nodes.Cube055_Cube059.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube054_Cube058"
        geometry={nodes.Cube054_Cube058.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube053_Cube057"
        geometry={nodes.Cube053_Cube057.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube052_Cube056"
        geometry={nodes.Cube052_Cube056.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube051_Cube055"
        geometry={nodes.Cube051_Cube055.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube050_Cube054"
        geometry={nodes.Cube050_Cube054.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube049_Cube053"
        geometry={nodes.Cube049_Cube053.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube048_Cube052"
        geometry={nodes.Cube048_Cube052.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube047_Cube051"
        geometry={nodes.Cube047_Cube051.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube046_Cube050"
        geometry={nodes.Cube046_Cube050.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube045_Cube049"
        geometry={nodes.Cube045_Cube049.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube044_Cube048"
        geometry={nodes.Cube044_Cube048.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube043_Cube047"
        geometry={nodes.Cube043_Cube047.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube042_Cube046"
        geometry={nodes.Cube042_Cube046.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube041_Cube045"
        geometry={nodes.Cube041_Cube045.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube040_Cube044"
        geometry={nodes.Cube040_Cube044.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube039_Cube043"
        geometry={nodes.Cube039_Cube043.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube038_Cube042"
        geometry={nodes.Cube038_Cube042.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube037_Cube041"
        geometry={nodes.Cube037_Cube041.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Plane045"
        geometry={nodes.Plane045.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane044"
        geometry={nodes.Plane044.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane043"
        geometry={nodes.Plane043.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane042"
        geometry={nodes.Plane042.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane041"
        geometry={nodes.Plane041.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane040"
        geometry={nodes.Plane040.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane039"
        geometry={nodes.Plane039.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane038"
        geometry={nodes.Plane038.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane037"
        geometry={nodes.Plane037.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane036"
        geometry={nodes.Plane036.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane033"
        geometry={nodes.Plane033.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane032"
        geometry={nodes.Plane032.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane031"
        geometry={nodes.Plane031.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane030"
        geometry={nodes.Plane030.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane029"
        geometry={nodes.Plane029.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane028_Plane020"
        geometry={nodes.Plane028_Plane020.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane027_Plane019"
        geometry={nodes.Plane027_Plane019.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane026_Plane017"
        geometry={nodes.Plane026_Plane017.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane025_Plane016"
        geometry={nodes.Plane025_Plane016.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane024_Plane015"
        geometry={nodes.Plane024_Plane015.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Cube036_Cube039"
        geometry={nodes.Cube036_Cube039.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube035_Cube038"
        geometry={nodes.Cube035_Cube038.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube034_Cube037"
        geometry={nodes.Cube034_Cube037.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube033_Cube036"
        geometry={nodes.Cube033_Cube036.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube032_Cube035"
        geometry={nodes.Cube032_Cube035.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube031_Cube034"
        geometry={nodes.Cube031_Cube034.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube030_Cube033"
        geometry={nodes.Cube030_Cube033.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube029_Cube032"
        geometry={nodes.Cube029_Cube032.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube028_Cube031"
        geometry={nodes.Cube028_Cube031.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube027_Cube030"
        geometry={nodes.Cube027_Cube030.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube026_Cube029"
        geometry={nodes.Cube026_Cube029.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube025_Cube028"
        geometry={nodes.Cube025_Cube028.geometry}
        material={materials.Fence}
      />
      <mesh
        name="Cube024_Cube027"
        geometry={nodes.Cube024_Cube027.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Cube023_Cube026"
        geometry={nodes.Cube023_Cube026.geometry}
        material={materials.Fence2}
      />
      <mesh
        name="Plane023_Plane014"
        geometry={nodes.Plane023_Plane014.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane022_Plane006"
        geometry={nodes.Plane022_Plane006.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane021_Plane005"
        geometry={nodes.Plane021_Plane005.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane020_Plane003"
        geometry={nodes.Plane020_Plane003.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Cylinder020_Cylinder030"
        geometry={nodes.Cylinder020_Cylinder030.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder019_Cylinder029"
        geometry={nodes.Cylinder019_Cylinder029.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder018_Cylinder028"
        geometry={nodes.Cylinder018_Cylinder028.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder017_Cylinder027"
        geometry={nodes.Cylinder017_Cylinder027.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder016_Cylinder026"
        geometry={nodes.Cylinder016_Cylinder026.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder015_Cylinder025"
        geometry={nodes.Cylinder015_Cylinder025.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cube017"
        geometry={nodes.Cube017.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube016"
        geometry={nodes.Cube016.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube015"
        geometry={nodes.Cube015.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube014"
        geometry={nodes.Cube014.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube013"
        geometry={nodes.Cube013.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube012"
        geometry={nodes.Cube012.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube011"
        geometry={nodes.Cube011.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube010"
        geometry={nodes.Cube010.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube009"
        geometry={nodes.Cube009.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube008"
        geometry={nodes.Cube008.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube007"
        geometry={nodes.Cube007.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube006_Cube005"
        geometry={nodes.Cube006_Cube005.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube005_Cube004"
        geometry={nodes.Cube005_Cube004.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube004_Cube003"
        geometry={nodes.Cube004_Cube003.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube003_Cube001"
        geometry={nodes.Cube003_Cube001.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Cube002_Cube"
        geometry={nodes.Cube002_Cube.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Plane019_Plane"
        geometry={nodes.Plane019_Plane.geometry}
        material={materials.Bark}
      />
      <mesh
        name="Plane018_Plane028"
        geometry={nodes.Plane018_Plane028.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane017_Plane027"
        geometry={nodes.Plane017_Plane027.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane016_Plane026"
        geometry={nodes.Plane016_Plane026.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane015_Plane025"
        geometry={nodes.Plane015_Plane025.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane013_Plane024"
        geometry={nodes.Plane013_Plane024.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane012_Plane023"
        geometry={nodes.Plane012_Plane023.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane011_Plane022"
        geometry={nodes.Plane011_Plane022.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Plane010_Plane021"
        geometry={nodes.Plane010_Plane021.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Cube_Cube006"
        geometry={nodes.Cube_Cube006.geometry}
        material={materials.CHIM}
      />
      <mesh
        name="Plane002_Plane004"
        geometry={nodes.Plane002_Plane004.geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane001_Plane002"
        geometry={nodes.Plane001_Plane002.geometry}
        material={materials.Sea}
      />
      <mesh
        name="Plane_Plane001"
        geometry={nodes.Plane_Plane001.geometry}
        material={materials.Material}
      />
      <mesh
        name="Plane035-Mesh"
        geometry={nodes["Plane035-Mesh"].geometry}
        material={materials.Mountain}
      />
      <mesh
        name="Plane035-Mesh_1"
        geometry={nodes["Plane035-Mesh_1"].geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane034-Mesh"
        geometry={nodes["Plane034-Mesh"].geometry}
        material={materials.Snow}
      />
      <mesh
        name="Plane034-Mesh_1"
        geometry={nodes["Plane034-Mesh_1"].geometry}
        material={materials.Mountain}
      />
      <mesh
        name="Cylinder014_Cylinder024-Mesh"
        geometry={nodes["Cylinder014_Cylinder024-Mesh"].geometry}
        material={materials.Bark}
      />
      <mesh
        name="Cylinder014_Cylinder024-Mesh_1"
        geometry={nodes["Cylinder014_Cylinder024-Mesh_1"].geometry}
        material={materials.Snow}
      />
      <mesh
        name="Cylinder014_Cylinder024-Mesh_2"
        geometry={nodes["Cylinder014_Cylinder024-Mesh_2"].geometry}
        material={materials.Pine}
      />
      <mesh
        name="Cylinder014_Cylinder024-Mesh_3"
        geometry={nodes["Cylinder014_Cylinder024-Mesh_3"].geometry}
        material={materials.Pine2}
      />
      <mesh
        name="Cube001_Cube002-Mesh"
        geometry={nodes["Cube001_Cube002-Mesh"].geometry}
        material={materials.Brown}
      />
      <mesh
        name="Cube001_Cube002-Mesh_1"
        geometry={nodes["Cube001_Cube002-Mesh_1"].geometry}
        material={materials.Window}
      />
      <mesh
        name="Cube001_Cube002-Mesh_2"
        geometry={nodes["Cube001_Cube002-Mesh_2"].geometry}
        material={materials.House}
      />
      <mesh
        name="Cube001_Cube002-Mesh_3"
        geometry={nodes["Cube001_Cube002-Mesh_3"].geometry}
        material={materials.Darker}
      />
      <mesh
        name="Cube001_Cube002-Mesh_4"
        geometry={nodes["Cube001_Cube002-Mesh_4"].geometry}
        material={materials.House1}
      />
      <mesh
        name="zSnowman_Icosphere204-Mesh"
        geometry={nodes["zSnowman_Icosphere204-Mesh"].geometry}
        material={materials["Snow.001"]}
      />
      <mesh
        name="zSnowman_Icosphere204-Mesh_1"
        geometry={nodes["zSnowman_Icosphere204-Mesh_1"].geometry}
        material={materials.Carrot}
      />

      <mesh
        name="zSnowman_Icosphere204-Mesh_2"
        geometry={nodes["zSnowman_Icosphere204-Mesh_2"].geometry}
        material={materials["Material.002"]}
      />
    </group>
  );
}

useGLTF.preload("/models/Camping Asset Collection.glb");
